project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd

format:
  html: 
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  acs-pdf: default

execute:
  freeze: true

editor: visual

