project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd
  code-links: 
    - text: GitHub Repo
      icon: github
      href: https://github.com/bgautijonsson/copulas
    - text: Stan Code
      icon: code
      href: https://github.com/bgautijonsson/copulas
    - text: R Package
      icon: code
      href: https://github.com/bgautijonsson/stdmatern
    

format:
  html: 
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  acs-pdf: default
 
execute:
  freeze: true

editor: source

